# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_players', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('round_length', models.DurationField()),
                ('approval_preference', models.PositiveIntegerField(choices=[(0, 'Admin'), (1, 'All')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alive', models.BooleanField(default=True)),
                ('membership_status', models.PositiveIntegerField(choices=[(0, 'Confirmed'), (1, 'Invited'), (2, 'Requested')])),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
