# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160220_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Game', max_length=20),
        ),
    ]
